# Disable purged architectures & legacy layers
WITHOUT_32BIT_LIBS=yes
WITHOUT_I386=yes
WITHOUT_KERBEROS=yes
WITHOUT_KERBEROS_SUPPORT=yes

# Disable purged bus/device drivers
WITHOUT_CARDBUS=yes
WITHOUT_PCCARD=yes
WITHOUT_FLOPPY=yes
WITHOUT_BLUETOOTH=yes
WITHOUT_WIRELESS=no

# Disable legacy/unused protocols & utilities
WITHOUT_NIS=yes
WITHOUT_TALK=yes
WITHOUT_TFTP=yes
